name: animated_switcher_plus
description: Prebuilt transitions for AnimatedSwitcher such as flip, zoom and translation
version: 1.1.0
homepage: https://github.com/hoomanmmd/animated_switcher_plus

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: